version: "3.0"
services:
  svn:
    image: mamohr/subversion-edge
    container_name: subversion-edge
    ports:
      - 18080:18080
      - 3343:3343
      - 4434:4434
    volumes:
      - ./data:/opt/csvn/data
    restart: unless-stopped
